NAME = libft.a
SRC_FOLDER = ./srcs
cc = cc -Wall -Wextra -Werror



# Tell make how to transform a .c file into a object file
.c.o:
	$(CC) $(FLAGS) -c $< -o ${<:.c=.o}


.PHONY: clean all fclean re so